apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: chronic-pony-nodejs 
  janus-idp.io/tekton: chronic-pony-nodejs
  backstage.io/kubernetes-id: chronic-pony-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: chronic-pony-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  